name: anomaly_detection_predict_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip:
    - mldesigner
    - pandas
    - pyod
    - joblib
    - matplotlib
    - numpy>=1.19
    - numba>=0.51
    - scipy>=1.5.1
    - scikit_learn>=0.20.0
    - six
    - statsmodels
    - combo
    - keras
    - tensorflow
    - torch
    - suod
    - xgboost